// This gulp is made for Processwire multisite projects

// including plugins
var gulp = require("gulp");
var less = require("gulp-less");
var scss = require("gulp-scss");
var sassbeautify = require('gulp-sassbeautify');
var concat = require("gulp-concat");
var stripDebug = require("gulp-strip-debug");
var uglify = require("gulp-uglify");
var minifyCss = require("gulp-minify-css");
var browserSync = require('browser-sync').create();

// Server
gulp.task('browser-sync', function () {
    browserSync.init({
        proxy: "siilak.dev"
    });
});

// Copy Uikit
gulp.task('copy', function () {
    gulp.src('./node_modules/uikit/**/*')
        .pipe(gulp.dest('./site/templates/'))
        .pipe(browserSync.stream());
});

// Copy Materialize
gulp.task('copy-material', function () {
    gulp.src('./node_modules/materialize-css/**/*')
        .pipe(gulp.dest('./site/templates/materialize-css/'))
        .pipe(browserSync.stream());
});

// Generate SVG icons
var svgSymbols = require('gulp-svg-symbols');
gulp.task('svg', function () {
    return gulp.src('core/svg/*.svg')
        .pipe(svgSymbols())
        .pipe(gulp.dest('core/svg'));
});

// Beautify your scss file
gulp.task('beautify', function () {
    gulp.src('./site/templates/css/**/*.scss')
        .pipe(sassbeautify())
        .pipe(gulp.dest('./site/templates/css/'));
});

// SCSS file to css
gulp.task("siilak", function () {
    gulp
        .src("./site/templates/css/www.scss") // path to your file
        .pipe(sassbeautify())
        .pipe(scss())
        .pipe(minifyCss())
        .pipe(gulp.dest("site/templates/css/"))
        .pipe(browserSync.stream());
});

gulp.task("robo", function () {
    gulp
        .src("./site-robo/templates/css/www.less") // path to your file
        .pipe(less())
        .pipe(minifyCss())
        .pipe(gulp.dest("site-robo/templates/css/"))
        .pipe(browserSync.stream());
});

gulp.task("admin", function () {
    gulp
        .src("./site/modules/theme/theme.scss") // path to your file
        .pipe(scss())
        .pipe(minifyCss())
        .pipe(gulp.dest("site/modules/theme"))
        .pipe(browserSync.stream());
});

// Work with scss files
gulp.task("default", function () {
    gulp.watch("./site/templates/**/*.scss", ["siilak"]);
    gulp.watch("./site/modules/theme/*.scss", ["admin"]);
});

// Copy js files to project
gulp.task("scripts", function () {
    gulp
        .src([
            "node_modules/jquery/dist/jquery.js",
            "node_modules/uikit/dist/js/uikit.js",
            "node_modules/uikit/dist/js/uikit-icons.js",
            "node_modules/plyr/dist/plyr.js",
            "node_modules/slick-carousel/slick/slick.js",
            "node_modules/masonry-layout/dist/masonry.pkgd.js",
            "node_modules/jquery-validation/dist/jquery.validate.js"
        ])
        .pipe(concat("www.js"))
        .pipe(stripDebug())
        .pipe(uglify())
        .pipe(gulp.dest("site/templates/js/"));
});

gulp.task("admin-scripts", function () {
    gulp
        .src([
            "node_modules/jquery/dist/jquery.js",
            "node_modules/materialize-css/dist/js/materialize.js"
        ])
        .pipe(concat("www.js"))
        .pipe(stripDebug())
        .pipe(uglify())
        .pipe(gulp.dest("site/modules/theme/js/"));
});
